# This is a basic workflow to help you get started with Actions

name: CheckStyle
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [ pull_request, push]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  analysis:
    name: CheckStyle
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11        
      #- name: Run Google Code Analysis Here
      #  run: java com.puppycrawl.tools.checkstyle.Main -c docs/google_checks.xml src/
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          checkstyle_config: checkstyle.xml
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check, github-check, github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need [info,warning,error].
          # GitHub Status Check won't become failure with a warning.
          level: warning
          #workdir: src/main
